### ISSUE TITLE
Organizing Classes and Files

### ISSUE THREAD

**Issue by mbahia** [UCSB-CS56-Projects/cs56-utilities-binary-clock#16]
Clean up all files, especially BinaryClock.java. The classes need to be separated into several different
files for better organization and efficiency. Also maximize is misspelt in the BinaryClock.java as well as in the 
program under 'Screen Settings'.

Points Suggested: 150 pts

**Comment by dcoffill** [comment]
Approved

**Comment by JohnUCSB** [comment]
F16 Approved  - 150 pts

**Comment by jimmylle** [comment]
Fixed with this [pull request](https://github.com/UCSB-CS56-Projects/cs56-utilities-binary-clock/pull/29).
