### ISSUE TITLE
Show Current Date

### ISSUE THREAD

**Issue by mbahia** [UCSB-CS56-Projects/cs56-utilities-binary-clock#17]
Enhance the program so that it becomes a Date and Time application. 
Do this by including the date shown in binary or in the standard mm/dd/yy form.
Points Suggested: 200 points

**Comment by dcoffill** [comment]
Approved

**Comment by JohnUCSB** [comment]
F16 Approved  - 200 pts

**Comment by jimmylle** [comment]
Fixed in this [pull request](https://github.com/UCSB-CS56-Projects/cs56-utilities-binary-clock/pull/31).
