### ISSUE TITLE
Creating new shapes

### ISSUE THREAD

**Issue by JohnUCSB** [UCSB-CS56-Projects/cs56-utilities-binary-clock#19]
The binaryclock program only has one shape (rectangle). It would be awesome if we can implement different shapes like triangle or circle. To do this, we will need to create a new class (e.g. Triangle.java class) and implement it in TimePanel.java. 

Suggested points: ~250

**Comment by dcoffill** [comment]
Approved

**Comment by JohnUCSB** [comment]
F16 Approved  - 250 pts

**Comment by xavierholt** [comment]
Did someone say Factory Pattern?

200 XP
