### ISSUE TITLE
Screen shot of the program

### ISSUE THREAD

**Issue by JohnUCSB** [UCSB-CS56-Projects/cs56-utilities-binary-clock#23]
Please add a picture of the binary clock for people who do not know what it is. 100 points

**Comment by JohnUCSB** [comment]
F16 Approved  - 100 pts

**Comment by jimmylle** [comment]
Fixed with this [pull request](https://github.com/UCSB-CS56-Projects/cs56-utilities-binary-clock/pull/24).
