### ISSUE TITLE
Make it look more visually stimulating

### ISSUE THREAD

**Issue by KevinL123** [UCSB-CS56-Projects/cs56-utilities-binary-clock#26]
The current project looks very outdated, change the project to look more modern and have better colors (~250 pts)

**Comment by jimmylle** [comment]
F16 OK (250 pts)

**Comment by jimmylle** [comment]
Fixed in this [pull request](https://github.com/UCSB-CS56-Projects/cs56-utilities-binary-clock/pull/31).
