### ISSUE TITLE
Add sound

### ISSUE THREAD

**Issue by KevinL123** [UCSB-CS56-Projects/cs56-utilities-binary-clock#27]
Make the project seem more like an actual clock by adding in sound. ie. ticking noise, a bell that rings hourly (~300 pts)

**Comment by jimmylle** [comment]
F16 OK (250 pts)

**Comment by jimmylle** [comment]
Fixed in this [pull request](https://github.com/UCSB-CS56-Projects/cs56-utilities-binary-clock/pull/32).
