### ISSUE TITLE
Improve GUI

### ISSUE THREAD

**Issue by bkiefer13** [UCSB-CS56-Projects/cs56-utilities-binary-clock#3]
Once the tutorial mode from #2 is working, add additional render layouts to choose from.

Some possible improvements may include:
-Support for additional block styles other than basic
-Better looking text labels for tutorial mode
-Windowless fullscreen support
etc.

~200 points

**Comment by mbahia** [comment]
Created separate issues for each GUI Improvement. (Issues #14, #15)
