### ISSUE TITLE
Refactor how TimePanel.java creates Blocks

### ISSUE THREAD

**Issue by shudaniel** [UCSB-CS56-Projects/cs56-utilities-binary-clock#62]
TimePanel.java hardcodes in every individual Block object for the clock. Each Block creation is copy pasted with different parameters. Currently, each Block is its own instance variable, so there are 20 Block instance variables. A majority of the code is copy pasted to do the same task on every single block.
Completely refactor entire class to be more flexible and follow DRY.

200-300 points.

**Comment by KevinLee00** [comment]
I'll give you 200 points for this.
