### ISSUE TITLE
More gradient

### ISSUE THREAD

**Issue by yantsey** [UCSB-CS56-Projects/cs56-utilities-binary-clock#7]
Right now, the gradient for the blocks only goes from the original blue/red to a slightly darker blue/red.

After this issue is completed, the gradient should go from the original blue/red to full black.

This has to do with the getDarker() method in Block.java. Where the RGB color values are decreased by 1, you need to change it to 2. Then you should go back to the for loop and change the number of rectangles you draw on top of each other, with each rectangle getting darker by the correct amount. Currently, if you decrement the color of each rectangle by 2, it will reach full black near the middle of the rectangle, and there will be errors. So find how many rectangles you will need to overlay on top of each other to create the full gradient effect, and make sure the gradient spans the entire block.

Estimated 150 pts (just my opinion)

**Comment by mbahia** [comment]
Completed and added to branch.
