### ISSUE TITLE
Fix flickering

### ISSUE THREAD

**Issue by yantsey** [UCSB-CS56-Projects/cs56-utilities-binary-clock#8]
When the GUI runs, some of the blocks flicker. This may have to do with how the gradient draws so many rectangles on top of each other. If you fix the gradient issue, that may reduce flickering. Also, you can easily reduce the flickering in the AM/PM blocks simply by creating an "AM/PM" timer that updates those blocks every 12 hours. Currently, it updates it every second, which is probably the cause of the flickering (in the AM/PM blocks only).

Note: these may not be the only causes of the flickering.

The code to fix this should be in BinaryClock.java and Block.java.
Estimated: 200 pts

**Comment by mbahia** [comment]
Completed and added to branch.
